### PR TITLE
some fix

### PR DESCRIPTION
**Pull request by NeoDarkness**

### CODE REVIEW

**Comment by NeoDarkness** [comment]
See like in miui https://drive.google.com/file/d/0B3-TxWGEp8N1SnpOVXJXTy1RZW8/view?usp=drivesdk

**Comment by NeoDarkness** [comment]
You have to revert this https://github.com/nicknitewolf/proprietary_vendor_wingtech/commit/e7fd284c35e634a884cf42ad8e8d0286c63601ab https://github.com/nicknitewolf/proprietary_vendor_wingtech/commit/4da7d33b4ecd10a7cb1e339985e8812a1254b735

**Comment by nicknitewolf** [comment]
Not acceptable

**Comment by NeoDarkness** [comment]
Why? What the reason?

**Comment by nicknitewolf** [comment]
I am not even using this tree

**Comment by nicknitewolf** [comment]
And the powerconfigs from miui is a big big error. Don't just blindly copy and paste

**Comment by nicknitewolf** [comment]
I'll do it myself to bring perfd back.

**Pull request closed without merging**
